import type { UAssetEnumEntry } from "@/main/types/uassets"

/**
 * Bit flags in `PackageFileSummary.PackageFlags`, refreshed against UE 5.8 source.
 * @see /Engine/Source/Runtime/CoreUObject/Public/UObject/ObjectMacros.h
 */
export const UAssetPackageFlags = {
    PKG_None: { value: 0x00000000, comment: "No flags" },
    PKG_NewlyCreated: { value: 0x00000001, comment: "Newly created package, not saved yet. In editor only." },
    PKG_ClientOptional: { value: 0x00000002, comment: "Purely optional for clients." },
    PKG_ServerSideOnly: { value: 0x00000004, comment: "Only needed on the server side." },
    PKG_CompiledIn: { value: 0x00000010, comment: 'This package is from "compiled in" classes.' },
    PKG_ForDiffing: { value: 0x00000020, comment: "This package was loaded just for the purposes of diffing" },
    PKG_EditorOnly: {
        value: 0x00000040,
        comment: "This is editor-only package (for example: editor module script package)",
    },
    PKG_Developer: { value: 0x00000080, comment: "Developer module" },
    PKG_UncookedOnly: { value: 0x00000100, comment: "Loaded only in uncooked builds (i.e. runtime in editor)" },
    PKG_Cooked: { value: 0x00000200, comment: "Package is cooked" },
    PKG_ContainsNoAsset: {
        value: 0x00000400,
        comment: "Package doesn't contain any asset object (although asset tags can be present)",
    },
    PKG_NotExternallyReferenceable: {
        value: 0x00000800,
        comment:
            "Objects in this package cannot be referenced in a different plugin or mount point (i.e /Game -> /Engine)",
    },
    PKG_AccessSpecifierEpicInternal: {
        value: 0x00001000,
        comment: "Objects in this package can only be referenced in a different plugin or mount point by Epic",
    },
    PKG_UnversionedProperties: {
        value: 0x00002000,
        comment: "Uses unversioned property serialization instead of versioned tagged property serialization",
    },
    PKG_ContainsMapData: {
        value: 0x00004000,
        comment: "Contains map data (UObjects only referenced by a single ULevel) but is stored in a different package",
    },
    PKG_IsSaving: { value: 0x00008000, comment: "Temporarily set on a package while it is being saved." },
    PKG_Compiling: { value: 0x00010000, comment: "package is currently being compiled" },
    PKG_ContainsMap: { value: 0x00020000, comment: "Set if the package contains a ULevel/ UWorld object" },
    PKG_RequiresLocalizationGather: {
        value: 0x00040000,
        comment: "Set if the package contains any data to be gathered by localization",
    },
    PKG_LoadUncooked: {
        value: 0x00080000,
        comment:
            "This package must be loaded uncooked from IoStore/ZenStore (set only when cooking, to communicate to zenstore via the PackageStoreOptimizer)",
    },
    PKG_PlayInEditor: { value: 0x00100000, comment: "Set if the package was created for the purpose of PIE" },
    PKG_ContainsScript: { value: 0x00200000, comment: "Package is allowed to contain UClass objects" },
    PKG_DisallowExport: { value: 0x00400000, comment: "Editor should not export asset in this package" },
    PKG_Unused_800000: { value: 0x00800000, comment: "Unused" },
    PKG_Unused_1000000: { value: 0x01000000, comment: "Unused" },
    PKG_Unused_2000000: { value: 0x02000000, comment: "Unused" },
    PKG_Unused_4000000: { value: 0x04000000, comment: "Unused" },
    PKG_CookGenerated: {
        value: 0x08000000,
        comment: "This package was generated by the cooker and does not exist in the WorkspaceDomain",
    },
    PKG_DynamicImports: {
        value: 0x10000000,
        comment: "Obsolete flag, deprecated in UE 5.8.",
    },
    PKG_RuntimeGenerated: {
        value: 0x20000000,
        comment:
            "This package contains elements that are runtime generated, and may not follow standard loading order rules",
    },
    PKG_ReloadingForCooker: {
        value: 0x40000000,
        comment:
            "This package is reloading in the cooker, try to avoid getting data we will never need. We won't save this package.",
    },
    PKG_FilterEditorOnly: { value: 0x80000000, comment: "Package has editor-only data filtered out" },
    PKG_TransientFlags: {
        value: 0x00000001 | 0x00008000 | 0x40000000,
        comment: "Transient Flags are cleared when serializing to or from PackageFileSummary",
    },
    PKG_InMemoryOnly: {
        value: 0x00000010 | 0x00000001,
        comment: "Flag mask that indicates if this package is a package that exists in memory only.",
    },
} as const satisfies Record<string, UAssetEnumEntry>
